<?php

$nombres = ['Antonio', 'María Carmen', 'María', 'Carmen', 'Ana María', 'Josefa', 'Isabel', 'María Pilar', 'María Dolores', 'Laura', 'María Teresa', 'Ana', 'Cristina', 'Marta', 'María Ángeles', 'Francisca', 'Lucia', 'María Isabel', 'María José', 'Antonia', 'Dolores', 'Sara', 'Paula', 'Elena', 'María Luisa', 'Raquel', 'Rosa María', 'Pilar', 'Concepción', 'Manuela', 'María Jesús', 'Mercedes', 'Julia', 'Beatriz', 'Nuria', 'Silvia', 'Rosario', 'Juana', 'Alba', 'Irene', 'Teresa', 'Encarnación', 'Patricia', 'Montserrat', 'Andrea', 'Roció', 'Mónica', 'Rosa', 'Alicia', 'María Mar', 'Sonia', 'Sandra', 'Ángela', 'Marina', 'Susana', 'Natalia', 'Yolanda', 'Margarita', 'María Josefa', 'Claudia', 'Eva', 'María Rosario', 'Inmaculada', 'Sofía', 'María Mercedes', 'Carla', 'Ana Isabel', 'Esther', 'Noelia', 'Verónica', 'Ángeles', 'Nerea', 'Carolina', 'María Victoria', 'Eva María', 'Inés', 'Miriam', 'María Rosa', 'Daniela', 'Lorena', 'Ana Belén', 'María Elena', 'María Concepción', 'Victoria', 'Amparo', 'María Antonia', 'Catalina', 'Martina', 'Lidia', 'Alejandra', 'Celia', 'María Nieves', 'Consuelo', 'Olga', 'Ainhoa', 'Fátima', 'Gloria', 'Emilia', 'María Soledad', 'Clara', 'María Cristina', 'Manuel', 'José', 'Francisco', 'David', 'Juan', 'José Antonio', 'Javier', 'Daniel', 'José Luis', 'Francisco Javier', 'Carlos', 'Jesús', 'Alejandro', 'Miguel', 'José Manuel', 'Rafael', 'Miguel Ángel', 'Pedro', 'Pablo', 'Ángel', 'Sergio', 'José María', 'Fernando', 'Jorge', 'Luis', 'Alberto', 'Juan Carlos', 'Álvaro', 'Adrián', 'Juan José', 'Diego', 'Raúl', 'Iban', 'Juan Antonio', 'Rubén', 'Enrique', 'Oscar', 'Ramón', 'Vicente', 'Andrés', 'Juan Manuel', 'Joaquín', 'Santiago', 'Víctor', 'Eduardo', 'Mario', 'Roberto', 'Jaime', 'Francisco José', 'Marcos', 'Ignacio', 'Alfonso', 'Jordi', 'Hugo', 'Ricardo', 'Salvador', 'Guillermo', 'Emilio', 'Gabriel', 'Marc', 'Gonzalo', 'Julio', 'Julián', 'Mohamed', 'José Miguel', 'Tomas', 'Martin', 'Agustín', 'José Ramón', 'Nicolás', 'Ismael', 'Joan', 'Félix', 'Samuel', 'Cristian', 'Aitor', 'Lucas', 'Héctor', 'Juan Francisco', 'Iker', 'Josep', 'José Carlos', 'Alex', 'Mariano', 'Domingo', 'Sebastián', 'Alfredo', 'Cesar', 'José Ángel', 'Felipe', 'José Ignacio', 'Víctor Manuel', 'Rodrigo', 'Luis Miguel', 'Mateo', 'José Francisco', 'Juan Luis', 'Xavier', 'Albert'];

$apellidos = ['García', 'Rodríguez', 'González', 'Fernández', 'López', 'Martínez', 'Sánchez', 'Pérez', 'Gómez', 'Martin', 'Jiménez', 'Ruiz', 'Hernández', 'Díaz', 'Moreno', 'Muñoz', 'Álvarez', 'Romero', 'Alonso', 'Gutiérrez', 'Navarro', 'Torres', 'Domínguez', 'Vázquez', 'Ramos', 'Gil', 'Ramírez', 'Serrano', 'Blanco', 'Molina', 'Morales', 'Suarez', 'Ortega', 'Delgado', 'Castro', 'Ortiz', 'Marín', 'Rubio', 'Sanz', 'Núñez', 'Medina', 'Iglesias', 'Cortes', 'Castillo', 'Garrido', 'Santos', 'Lozano', 'Guerrero', 'Cano', 'Prieto', 'Méndez', 'Cruz', 'Flores', 'Herrera', 'Gallego', 'Márquez', 'León', 'Peña', 'Calvo', 'Cabrera', 'Vidal', 'Campos', 'Vega', 'Fuentes', 'Carrasco', 'Reyes',  'Herrero', 'Montero', 'Hidalgo', 'Giménez', 'Lorenzo', 'Ibáñez', 'Vargas', 'Santiago', 'Duran', 'Ferrer', 'Benítez', 'Mora', 'Arias', 'Vicente', 'Carmona', 'Crespo', 'Román', 'Soto', 'Pastor', 'Velasco', 'Sáez', 'Rojas', 'Moya', 'Parra', 'Soler', 'Bravo', 'Gallardo', 'Esteban', 'Pardo', 'Rivera', 'Franco', 'Merino', 'Rivas', 'Lara', 'Silva', 'Espinosa', 'Izquierdo', 'Camacho', 'Vera', 'Arroyo', 'Casado', 'Ríos', 'Redondo', 'Mendoza', 'Luque', 'Galán', 'Rey', 'Sierra', 'Montes', 'Otero', 'Segura', 'Carrillo', 'Marcos', 'Soriano','Diez', 'Caballero', 'Nieto', 'Aguilar', 'Santana', 'Pascual', 'Bernal', 'Martí', 'Heredia', 'Robles', 'Valero', 'Vila', 'Palacios', 'Macías', 'Expósito', 'Contreras', 'Guerra', 'Varela', 'Benito', 'Roldan', 'Pereira', 'Mateo', 'Bueno', 'Andrés', 'Miranda', 'Villar', 'Guillen', 'Aguilera', 'Mateos', 'Escudero', 'Casas', 'Rivero', 'Padilla', 'Aparicio', 'Calderón', 'Acosta', 'Estévez', 'Beltrán', 'Salazar', 'Gálvez', 'Menéndez', 'Salas', 'Rico', 'Guzmán', 'Jurado', 'Conde', 'Bermúdez', 'Gracia', 'Quintana', 'Abad', 'Aranda', 'Plaza', 'Blázquez', 'Santamaría', 'Ávila', 'Roca', 'Manzano', 'Trujillo', 'Costa', 'Hurtado', 'Villanueva', 'Pacheco', 'Miguel', 'Serra', 'Rueda', 'Cuesta', 'Escobar', 'Tomas', 'Mesa', 'De La Fuente', 'Simón', 'Del Rio', 'Luna', 'Lázaro', 'Pons', 'Alarcón', 'Sancho', 'Millán', 'Zamora', 'Castaño'];



$perros = ['Luna', 'Kira', 'Lola', 'Nala', 'Bimba', 'Noa', 'Maya', 'Mia', 'Duna', 'Gala', 'Trufa', 'Dana', 'Nina', 'Kiara', 'Bella', 'Canela', 'Lua', 'Frida', 'Lia', 'Laika', 'Pepa', 'Arya', 'Nana', 'Linda', 'Dama', 'Leia', 'Kyra', 'Tara', 'Lana', 'Coco', 'Mika', 'Tina', 'India', 'Nora', 'Rita', 'Sasha', 'Chispa', 'Greta', 'Lluna', 'Pipa', 'Chloe', 'Cora', 'Lula', 'Kala', 'Cloe', 'Sira', 'Zoe', 'Lucy', 'Kika', 'Nela', 'Tana', 'Nube', 'Mía', 'Maggie', 'Cleo', 'Molly', 'Shiva', 'Uma', 'Perla', 'Kora', 'Tula', 'Rumba', 'Olivia', 'Ona', 'Sansa', 'Bruna', 'Roma', 'Mora', 'Lulu', 'Hera', 'Aria', 'Nuka', 'Nika', 'Dora', 'Neska', 'Jara', 'Chanel', 'Lara', 'Freya', 'Wendy', 'Noah', 'Samba', 'Xena', 'Boira', 'Reina', 'Lili', 'Milka', 'Alma', 'Lía', 'Cala', 'Mila', 'Lila', 'Princesa', 'Shira', 'Vera', 'Mel', 'Blanca', 'Chica', 'Daisy', 'Akira', 'Thor', 'Coco', 'Max', 'Leo', 'Bruno', 'Rocky', 'Zeus', 'Lucas', 'Toby', 'Simba', 'Otto', 'Lucky', 'Pancho', 'Lolo', 'Golfo', 'Jack', 'Pepe', 'Tango', 'Ron', 'Pipo', 'Duque', 'Baloo', 'Cooper', 'Yako', 'Buddy', 'Ares', 'Bruce', 'Milo', 'Rocco', 'Curro', 'Chester', 'Teo', 'Sam', 'Nano', 'Blacky', 'Nico', 'Dante', 'Neo', 'Romeo', 'Chico', 'Django', 'Rufo', 'Duke', 'Luca', 'Goku', 'Blue', 'Marley', 'Rex', 'Kai', 'Roco', 'Paco', 'Odin', 'Tyson', 'Dexter', 'Oreo', 'Charlie', 'Gus', 'Elvis', 'Choco', 'Trasto', 'Robin', 'Drako', 'Roy', 'Loki', 'Gordo', 'Kiko', 'Danko', 'Lobo', 'Hugo', 'Draco', 'Terry', 'Tito', 'Teddy', 'Cholo', 'Fito', 'Bob', 'Rayo', 'Pluto', 'Enzo', 'Black', 'Pongo', 'Ringo', 'Niko', 'Tommy', 'Tayson', 'Lennon', 'Oscar', 'Troy', 'Tobi', 'Boss', 'Apolo', 'Bowie', 'Bobby', 'Willy', 'Bimbo', 'Happy', 'Scooby', 'Balto', 'Toy', 'Dobby'];

$gatos = ['Huevete', 'Thelmo', 'Borya', 'Cástor', 'Azor', 'Eros', 'Eneas', 'Dooham', 'Manchas', 'Hōkō', 'Hades', 'Moulet', 'Axel', 'Davit', 'Gringo', 'Mickey', 'Karim', 'Totoro', 'Elmer', 'Villa', 'Binky', 'Señor Furia', 'Parkour', 'Mambo', 'Akron', 'Skipper', 'Totó', 'Kerchak', 'Cobi', 'Max', 'Fedello', 'Suini', 'Kripton', 'Tango', 'Chamán', 'Alf', 'Akira', 'Kal-El', 'Cronos', 'Gastón', 'Keita', 'Miliki', 'Zurisadahi', 'Boby', 'Sugar', 'Diamante', 'Bond', 'Blas', 'Acero', 'Dumbo', 'Elur', 'Garras', 'Ares', 'Shere Khan', 'Bowie', 'Ferrero', 'Haro', 'Absolem', 'Atum', 'Flanders', 'Davor', 'Adán', 'Oreo', 'Alai', 'Emmet', 'Mimo', 'Noir', 'Eclipse', 'Joker', 'Chuky', 'Luck', 'Curro', 'Han Solo', 'Zack', 'Spot', 'Willy', 'Atila', 'Tiger', 'Cooper', 'Febo', 'Timón', 'Robin', 'Summer', 'Pooky', 'Teo', 'Akamaru', 'Simba', 'Harvey', 'Vuvú', 'Newman', 'Dédalo', 'Tomy', 'Ra', 'Herodes', 'Astor', 'Ramsés', 'Genio', 'Bécquer', 'Byron', 'Backet', 'Hache', 'Lioh', 'Chucky', 'Poncho', 'Lennox', 'Dalí', 'Boss', 'Sosis', 'Lázaro', 'Horus', 'Hércules', 'Pumba', 'Jordan', 'Lory Mony', 'Geppetto', 'Lobo', 'Rumble', 'Koala', 'Gray', 'Malphite', 'Bichi', 'Lambo', 'Tritón', 'Viento', 'Kiko', 'Tizón', 'Hommer', 'Sisuko', 'Orellana', 'Lolito', 'Rexi', 'Nesquick', 'Cola-cao', 'Oreo', 'Félix', 'Nero', 'Ninja', 'Batman', 'Sombra', 'Silvestre', 'Choco', 'Mágico', 'Leo', 'Adrien', 'Espresso', 'Dylan', 'Bombo', 'Adonis', 'Aldo', 'Aquiles', 'Algodón', 'Capuccino', 'Grumete', 'Pitingo', 'Pulgoso', 'Capone', 'Zape', 'Ashira', 'Duque', 'Fluffy', 'Lucky Luke', 'Dagda', 'Presidente Miau', 'Gohan', 'Waffle', 'Happy', 'Yuriko', 'Broadway', 'Quesito', 'Silvestre', 'Nemui', 'Zipi', 'Thelmo', 'Manchas', 'Totoro', 'Villa', 'Señor Furia', 'Kerchak', 'Fedello', 'Baloo', 'Brandy', 'Dandi', 'Adonis', 'Copérnico', 'Bubba', 'Aldo', 'Frodo', 'Fofó', 'Algodón', 'Aquiles', 'Bam-Bam', 'Dátil', 'Golfo', 'Donald', 'Fofito', 'Bunner', 'Capuccino', 'Toby', 'Jazz', 'Copito'];


for ($i=0; $i < 200; $i++) { 
    $insert = "(";
    $insert .= "'" . $perros[$i] ."', ";
    $insert .= (random_int(5, 25)/10) . ", ";
    $insert .= "'" . $nombres[$i] ." " . $apellidos[$i] ."', ";
    $insert .= random_int(1, 10) . "),<br>";
    echo $insert;   
}